a parent b TEST
a parent c TEST
c parent e TEST
c parent f TEST
d parent c TEST
g parent h TEST
a related b TEST
a related c TEST
a related e TEST
a related f TEST
f related a TEST
a related a TEST
d related b TEST
h related g TEST